use crate::event::{EventKind, EventPayload};
use std::marker::PhantomData;

#[doc(hidden)]
pub mod sealed {
    pub trait Sealed {}
}

/// Marker trait for states that may appear in typed transitions.
///
/// This is sealed: only state types generated by the library's typestate
/// macros can implement it.
pub trait StateMarker: sealed::Sealed {}

/// Transition<From, To, P>: a typed state change with an EventKind and payload.
/// The compiler ensures transition endpoints are declared typestate markers,
/// not arbitrary product types.
pub struct Transition<From: StateMarker, To: StateMarker, P> {
    kind: EventKind,
    payload: P,
    _from: PhantomData<From>,
    _to: PhantomData<To>,
}

impl<From: StateMarker, To: StateMarker, P> Transition<From, To, P> {
    /// Creates a new transition with the given event kind and payload.
    pub fn new(kind: EventKind, payload: P) -> Self {
        Self {
            kind,
            payload,
            _from: PhantomData,
            _to: PhantomData,
        }
    }

    /// Returns the event kind for this transition.
    pub fn kind(&self) -> EventKind {
        self.kind
    }
    /// Returns a reference to the transition payload.
    pub fn payload(&self) -> &P {
        &self.payload
    }
    /// Consumes the transition and returns the payload.
    pub fn into_payload(self) -> P {
        self.payload
    }
}

impl<From: StateMarker, To: StateMarker, P: EventPayload> Transition<From, To, P> {
    /// Create a transition from a typed payload — kind derived from `P::KIND`.
    pub fn from_payload(payload: P) -> Self {
        Self::new(P::KIND, payload)
    }
}
